test : collision.cpp display.cpp draw.cpp game.cpp update.cpp global.cpp
	g++ -o run collision.cpp display.cpp draw.cpp game.cpp update.cpp global.cpp -lgsl -lgslcblas -lm -lglut -lGL -lGLU

clean :
	rm run
